# Generated by Django 3.1.6 on 2021-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='subscribed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
