# Generated by Django 3.1.6 on 2021-03-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210304_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_entry',
            field=models.DateField(auto_now_add=True),
        ),
    ]
