# Generated by Django 3.1.6 on 2021-03-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='order_id',
        ),
    ]
