# Generated by Django 3.1.6 on 2021-03-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210321_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='generated_id',
        ),
    ]
