# Generated by Django 3.1.6 on 2021-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210403_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'paypal'), ('Razorpay', 'razorpay'), ('Custom', 'custom')], max_length=15),
        ),
    ]
