# Generated by Django 3.1.6 on 2021-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210504_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('razorpay', 'Razorpay'), ('custom', 'Custom')], max_length=15),
        ),
    ]
