# Generated by Django 3.1.6 on 2021-05-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210504_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_of_entry', '-paid', '-id']},
        ),
    ]
