# Generated by Django 3.1.6 on 2021-05-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210504_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_of_entry', '-id']},
        ),
    ]
