# Generated by Django 3.1.6 on 2021-02-19 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(null=True)),
                ('stock', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='images/products/')),
                ('date_of_entry', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('message', models.TextField(blank=True, null=True)),
                ('date_of_entry', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
