# Generated by Django 3.1.6 on 2021-03-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210305_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_entry',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
